### ISSUE TITLE
babel-plugin-webpack-alias error between vue-jest@^2 and vue-jest@^3

### ISSUE THREAD

**Issue by illepic** [vuejs/vue-jest#119]
[babel-plugin-webpack-alias](https://github.com/trayio/babel-plugin-webpack-alias) provides webpack aliases to babel, allowing jest to understand aliases effectively as `moduleNameMapper` entries. This means that instead of referencing a module like:

```js
import card from '../../02-molecules/subfolder/card.vue';
```

we can do this instead: 

```js
import card from 'molecules/subfolder/card.vue';
```

Given webpack config that defines some aliases:

**./webpack.particle.js**
```javascript
module.exports = {
  // ...
  resolve: {
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      // Shorthand to import modules, i.e. `import thing from 'atoms/thing';`
      protons: path.resolve(PATH_PATTERNS, '00-protons/'),
      atoms: path.resolve(PATH_PATTERNS, '01-atoms/'),
      molecules: path.resolve(PATH_PATTERNS, '02-molecules/'),
      organisms: path.resolve(PATH_PATTERNS, '03-organisms/'),
      templates: path.resolve(PATH_PATTERNS, '04-templates/'),
      pages: path.resolve(PATH_PATTERNS, '05-pages/'),
    },
  }
};
```

And Babel config like so:

**./.babelrc**
```json
{
  "presets": [
    [
      "@babel/preset-env",
      { "useBuiltIns": "entry" }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-class-properties"
  ],
  "env": {
    "test": {
      "plugins": [
        [ "babel-plugin-webpack-alias", { "config": "./webpack.particle.js" } ]
      ]
    }
  }
}
```

`vue-jest@^2` runs all tests flawlessly. `vue-jest@^3` runs almost all tests, but fails for a very particular case, with the error:

```bash
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

      at PluginPass.CallExpression (node_modules/babel-plugin-webpack-alias/build/index.js:143:90)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
```

![image](https://user-images.githubusercontent.com/295127/47166631-7fcd3780-d2b1-11e8-9228-d689ded461bd.png)

For this particular Vue component, we're actually using aliases IN the `<script>` tag, causing the failure:

**./source/_patterns/02-molecules/vue-widget/src/vue-cards/components/banner.vue**
```vue
<template></template>
<script>
import { randRGB } from 'protons/utilities'; // 💥KABOOOM 💥

export default {
  // ...
  methods: {
    randomColor() {
      return `rgba(${randRGB()},${randRGB()},${randRGB()},1)`;
    },
  },
};
</script>
<style></style>
```

I can verify that removing the babel-plugin-webpack-alias config from `./babelrc` and manually adding in all Jest `moduleMapper` entries works again. Basically:

**jest.config.js**
```js
module.exports = {
  verbose: true,
  testURL: 'http://localhost/',
  setupFiles: ['<rootDir>/tools/tests/unit/setupJest.js'],
  // moduleFileExtensions: ['js', 'json', 'vue'],
  moduleNameMapper: {
    '^protons[/]?(.*)': '<rootDir>/source/_patterns/00-protons/$1',
    '^atoms/(.+)': '<rootDir>/source/_patterns/01-atoms/$1',
    '^molecules/(.+)': '<rootDir>/source/_patterns/02-molecules/$1',
    '^organisms/(.+)': '<rootDir>/source/_patterns/03-organisms/$1',
    '^templates/(.+)': '<rootDir>/source/_patterns/04-templates/$1',
    '^pages/(.+)': '<rootDir>/source/_patterns/05-pages/$1',
  },
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.vue$': 'vue-jest',
  },
};
```

^^This manual config works for `vue-jest@^3`.

**Comment by eddyerburgh** [comment]
Could you please provide a runnable reproduction using 4.0.0-beta.0?
