### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by Himself65** [vuejs/vue-jest#132]
I try to test my repo but have something wrong on `vue-jest`.

```js
import BCard from '@/components/src/BCard/BCard'

describe('BCard', () => {
  test('BCard test 1', () => {
    // const wrapper = mount(BCard)
    // expect(wrapper.isVueInstance()).toBeTruthy()
  })
})
```

``` bash
> yarn test
yarn run v1.12.3
$ node build/run-tests.js
$ cross-env NODE_ENV=test jest -i
 PASS  tests/unit/utils/index.test.js
 FAIL  tests/unit/components/bcard.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'includes' of undefined

      at node_modules/babel-plugin-module-resolver/lib/normalizeOptions.js:148:22
      at node_modules/reselect/lib/index.js:86:37
      at node_modules/reselect/lib/index.js:36:25
      at PluginPass.pre (node_modules/babel-plugin-module-resolver/lib/index.js:53:60)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:78:27)
      at runSync (node_modules/@babel/core/lib/transformation/index.js:45:3)
      at transformSync (node_modules/@babel/core/lib/transform.js:43:38)
      at Object.transform (node_modules/@babel/core/lib/transform.js:22:38)
      at compileBabel (node_modules/vue-jest/lib/compilers/babel-compiler.js:21:21)
      at processScript (node_modules/vue-jest/lib/process.js:30:10)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.255s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

and `BCard/index.js` are

```js
import BCard from './BCard.vue'

export default BCard
```

and `packpack.json`

```json
{
  "name": "kuen",
  "scripts": {
    "lint": "eslint ./backpacks/*/src/**/* --ext .vue,.js",
    "build": "concurrently \"yarn components:build \" \" yarn docs:build \"",
    "components:build": "rimraf backpacks/components/dist && cd backpacks/components && yarn build",
    "test": "node build/run-tests.js",
    "test:unix": "cross-env NODE_ENV=test jest",
    "test:win32": "cross-env NODE_ENV=test jest -i",
    "test:coverage": "yarn test --coverage",
    "dev": "vue-cli-service serve --open",
    "docs:dev": "vuepress dev docs --port 3005",
    "docs:build": "vuepress build docs"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.6",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@types/jest": "^23.3.9",
    "@types/node": "^10.11.3",
    "@types/vue": "^2.0.0",
    "@vue/cli-plugin-babel": "^3.1.1",
    "@vue/cli-plugin-eslint": "^3.1.5",
    "@vue/cli-plugin-unit-jest": "^3.1.1",
    "@vue/cli-service": "^3.1.4",
    "@vue/test-utils": "^1.0.0-beta.26",
    "avoriaz": "^6.3.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-polyfill": "^6.26.0",
    "concurrently": "^4.1.0",
    "cross-env": "^5.2.0",
    "eslint": "^5.6.1",
    "eslint-config-standard": "^12.0.0",
    "eslint-import-resolver-babel-module": "^4.0.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^4.7.1",
    "jest": "^23.6.0",
    "jest-css-modules": "^1.1.0",
    "jest-serializer-vue": "^2.0.2",
    "regenerator-runtime": "^0.13.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "tslint": "^5.11.0",
    "tslint-config-standard": "^8.0.1",
    "typescript": "^3.1.1",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vue-template-compiler": "^2.5.17",
    "vuepress": "^0.14.5"
  },
  "peerDependencies": {
    "vue": "^2.5.10"
  }
}
```

and `babel.config.js`

```js
module.exports = {
  plugins: [
    "@babel/plugin-transform-runtime",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
    "transform-vue-jsx"
  ],
  env: {
    build: {
      presets: [
        "@vue/app"
      ]
    },
    test: {
      plugins: [
        [
          "module-resolver",
          {
            root: [
              "./backpacks"
            ],
            alias: {
              "~components": "./components/src"
            },
            extensions: [
              '', '.vue', '.js', '.json'
            ]
          }
        ]
      ],
      presets: [
        [
          "@babel/env",
          {
            "targets": {
              "node": "current"
            },
          },
        ]
      ]
    }
  }
}
```

`jest.config.js`

```
module.exports = {
  verbose: false,
  roots: [
    '<rootDir>/backpacks/components/src',
    '<rootDir>/tests/unit'
  ],
  moduleFileExtensions: [
    "js",
    "json",
    "vue"
  ],
  moduleDirectories: ['node_modules'],
  moduleNameMapper: {
    '^@/test$': '<rootDir>/test/index.js',
    '^@/test/(.*)$': '<rootDir>/test/$1',
    '^@/(.*)$': '<rootDir>/backpacks/$1'
  },
  transform: {
    "\\.(js)$": "babel-jest",
    "\\.(vue)$": "vue-jest",
    '\\.(styl)$': 'jest-css-modules'
  },
  collectCoverageFrom: [
    "backpacks/**/*.{js,vue}",
    "!**/node_modules/**"
  ],
  snapshotSerializers: [
    "jest-serializer-vue"
  ],
  coverageReporters: ["html", "text-summary"],
  transformIgnorePatterns: [
    'node_modules/(?!vue-router)'
  ]
}
```

**Comment by Himself65** [comment]
I have found the reason, and it's my mistake

**Comment by VivatRafa** [comment]
I have same problem, is was wrong way to vue component

**Comment by VivatRafa** [comment]
> I have found the reason, and it's my mistake

Can you tell what the mistake was? @Himself65

**Comment by Himself65** [comment]
@VivatRafa 
I remove the `babel.config.js`

I thought it will conflict with config which on `vue-cli`

**Comment by VivatRafa** [comment]
@Himself65 Thank you very much!
