### ISSUE TITLE
Cannot find module 'convert-source-map'

### ISSUE THREAD

**Issue by wbern** [vuejs/vue-jest#172]
```
  * Test suite failed to run
    Cannot find module 'convert-source-map'
      at Object.<anonymous> (../../../common/temp/node_modules/.artifactory.dc.teliacompany.net/vue-jest/3.0.4/a8ad1c11314ee989f37a031897ab9024/node_modules/vue-jest/lib/process.js:14:26)
      at Object.<anonymous> (../../../common/temp/node_modules/.artifactory.dc.teliacompany.net/vue-jest/3.0.4/a8ad1c11314ee989f37a031897ab9024/node_modules/vue-jest/vue-jest.js:1:17)
```

vue-jest's package.json doesn't include this package, yet it is being required in process.js.

This causes errors when you use pnpm which eliminates all phantom dependencies.

Sorry for not providing a repro, I was hoping the issue is clear enough without repro.

**Comment by eddyerburgh** [comment]
Thanks for the report, would you like to create a PR adding convert-source-map as an explicit dependency?
