### ISSUE TITLE
tsconfig.json with no compilerOptions causes typescript-compiler to error

### ISSUE THREAD

**Issue by obermillerk** [vuejs/vue-jest#242]
I had a `tsconfig.json` with no `compilerOptions`, which typescrpit explicitly allows ([docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details)), and results in using the default values for all optoins.

When importing a `.vue` file in my test, it would throw the following error:

```
● Test suite failed to run

        TypeError: Cannot read property 'module' of undefined

      at compileTypescript (node_modules/vue-jest/lib/compilers/typescript-compiler.js:19:32)
      at processScript (node_modules/vue-jest/lib/process.js:23:12)
      at Object.module.exports [as process] (node_modules/vue-jest/lib/process.js:42:18)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:481:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:586:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:624:25)
```

If you look at the `typescript-compiler.js` line it references, there is a clear use of `tsConfig.compilerOptions.module` with no check whatsoever that `compilerOptions` is defined, which causes the error.

I have since added a `compilerOptions` field to my config for other reasons and it works fine onw, but wanted to let you guys know!

**Comment by kahirokunn** [comment]
I got the same error :cry:

**Comment by AverageHelper** [comment]
Same issue here. I started getting this error when transitioning to a solution-style tsconfig.json file, which does not require the `compilerOptions` field. Adding an empty object for that key fixed this error.

**Comment by lmiller1990** [comment]
I can try look at this soon. Is this for vue-jest 4.x or 5.x? (or both)?

If anyone is interested, would be happy to review/offer guidance!

**Comment by AverageHelper** [comment]
> Is this for vue-jest 4.x or 5.x? (or both)?

@lmiller1990 On consulting the README, it seems that there are versions of vue-jest greater than 3. Now I am confused... the `@latest` build from npm is 3.0.7.

Has this issue already been fixed? If so, how should I install the latest version of vue-jest?

**Comment by lmiller1990** [comment]
We should update the latest version on npm... unsure why this hasn't been done, I will need to see if there is any specific reason npm is sitting on 3.x (this repo was larger unmaintained for quite a while, I'm just picking this up). 

You want 4.x for Vue 2 and 5.x for Vue 3. 3.x has not received an update in quite some time.

**Comment by AverageHelper** [comment]
In the meantime, is there a 4.x version or git tag we should install via npm? My company's project is in Vue 2 atm

**Comment by lmiller1990** [comment]
Just do `yarn add vue-jest@4` and grab the latest one, beta something.

**Comment by TheDutchCoder** [comment]
I have installed 5.0.0 alpha 7 and I'm getting this error both locally and on github currently, even though (afaict) I didn't change anything other than do a npm install
