### ISSUE TITLE
Incorrect type for inputSourceMap

### ISSUE THREAD

**Issue by vlechemin** [vuejs/vue-jest#417]
Empty source map doesn't pass babel validator:
https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-core/src/config/validation/option-assertions.ts#L174

Due to empty string instead of undefined:
https://github.com/vuejs/vue-jest/blob/master/packages/vue3-jest/lib/transformers/typescript.js#L25
Should be:
`res.sourceMapText !== undefined ? JSON.parse(res.sourceMapText) : undefined`

**Comment by marcjfj** [comment]
Is there a workaround for this? I'm currently unable to run tests for SFCs that have lang="ts" in the script tag.

**Comment by lptai** [comment]
I got this error when running with my simple component 

```
<template>
  <button>
    <slot></slot>
  </button>
</template>

<script lang="ts">
export default {
  data() {
    return {
      name: '',
    };
  },
};
</script>
<style lang="scss" scoped>
@use 'sass:map';
@import '@styles/bases/_variables.scss';
@import '@styles/bases/_mixins.scss';

button {
  // my styling
}
</style>

```

```
.inputSourceMap must be a boolean, object, or undefined

      at assertInputSourceMap (node_modules/@babel/core/lib/config/validation/option-assertions.js:124:11)
      at node_modules/@babel/core/lib/config/validation/options.js:118:5
          at Array.forEach (<anonymous>)
```

My `jest.config.js`
```
...
transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '.*\\.(vue)$': '@vue/vue3-jest',
  },
...
```

**Comment by KushibikiMashu** [comment]
> UPDATED:
> It worked after enabling "sourceMap": true in tsconfig.json

It works! Thank you. The part of jest.config.js is below.

```
transform: {
  "^.+\\.js$": "babel-jest",
  ".*\\.(vue)$": "@vue/vue2-jest"
},
```
