### ISSUE TITLE
Error parsing scss with v2.0.0

### ISSUE THREAD

**Issue by iwata** [vuejs/vue-jest#51]
I met some strange errors, when upgraded from v1.4.0 to v2.0.0.
It occurs errors about parsing css, looks like this:

```
 FAIL  test/App.spec.js
  ● Test suite failed to run

    undefined:62:6: property missing ':'

      at error (node_modules/css/lib/parse/index.js:62:15)
      at declaration (node_modules/css/lib/parse/index.js:223:33)
      at declarations (node_modules/css/lib/parse/index.js:252:19)
      at rule (node_modules/css/lib/parse/index.js:560:21)
      at rules (node_modules/css/lib/parse/index.js:117:70)
      at stylesheet (node_modules/css/lib/parse/index.js:81:21)
      at Object.module.exports [as parse] (node_modules/css/lib/parse/index.js:564:20)
      at Function.extractClasses (node_modules/extract-from-css/lib/index.js:14:23)
      at processStyle (node_modules/vue-jest/lib/process.js:40:31)
      at parts.styles.map.ast (node_modules/vue-jest/lib/process.js:105:24)
```

Here is a part of `App.vue`:
```scss
62: ul {
63:   @include clearfix;
64: }
```

I use `sass-resources-loader` to set global mixin for SCSS.
I think it caused with not loading the mixin, but [README.md](https://github.com/vuejs/vue-jest/blob/master/README.md) told me 'It does not currently compile the style section'.
This makes me confused.
Incidentally, this error did not occur with v1.4.0.

Is there any good solution?

**Comment by nirkki** [comment]
Do you have nested classes in your scss?
I moved my nested classes to flat structure - and the message was gone.

**Comment by Finrod927** [comment]
I have the same issue using less and using flat structure did not help.

Back to 1.4.0 as I do not use Babel 7 for now.

**Comment by alajfit** [comment]
I have the same issue but moving to flat structure fixes the issue

**Comment by adamwoodbury** [comment]
I am having the same problem. If I have the following style block:
```
<style lang="scss">
  @import "~@/styles/transitions";
</style>
```
I get an error `undefined:30:1: missing '{'`. If I add a a css rule with a `{`:
```
<style lang="scss">
  @import "~@/styles/transitions";
  .app {
    // empty ruleset
  }
</style>
```
The error changes to `undefined:32:6: property missing ':'`. Finally, adding actual rules with a `:` will work:
```
<style lang="scss">
  @import "~@/styles/transitions";
  .app {
    color: blue;
  }
</style>
```
It looks like the library used for parsing the css is failing when it doesn't see an actual css rule.

**Comment by tforssander** [comment]
Same issue here using nested selectors. Went back to v1.4.0 and the error is gone.

**Comment by mrliptontea** [comment]
Yup, there is no support for Sass/SCSS at all. And in general support for <style> has been added recently in 7791d8e52f964416d3b3539e6fc79156d55e62fe, ie after 1.4.0.

Maybe it should test whether given `lang` is supported and skip styles entirely if it isn't? That would resolve the issue for now. Possibly emit a warning too, so devs would know what's going on and hint that such support might be added in the future.

**Comment by eddyerburgh** [comment]
Thanks for the details guys.

As a temporary solution we skip any scss or sass styles in 2.0.1, and throw a warning that it isn't compiled.

I'll keep this issue open as we should add support for SCSS now that styles are being compiled.

**Comment by abhipanda** [comment]
@eddyerburgh Thanks for supporting this feature, would you happen to know when can we expect 2.1.0, as its a blocker for us. 

Alternatively, I tried with  ".*\\.(vue)$": "jest-vue-preprocessor" and it works for now.

**Comment by eddyerburgh** [comment]
In 2.2.x we compile SCSS to add classes to the $`style` object.

**Comment by jeremyzahner** [comment]
@eddyerburgh I guess we can close this after merging https://github.com/vuejs/vue-jest/pull/82

**Comment by jeremyzahner** [comment]
@iwata Do you still have this issue after the rewrite of the SASS/SCSS compiler? If not, feel free to close this issue. =)
