### ISSUE TITLE
Failed to collect coverage: ERROR: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by mariangemarcano** [vuejs/vue-jest#60]
I'm hitting the following issue when running jest with code coverage:

Running coverage on untested files...Failed to collect coverage from components
/AppFooter.vue
ERROR: Unexpected token u in JSON at position 0
STACK: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at compileTypescript (src/node_modules/vue-jest/lib/compilers/typescript-compiler.js:67:44)
    at processScript (src/node_modules/vue-jest/lib/process.js:22:12)
    at Object.module.exports [as process] (src/node_modules/vue-jest/lib/process.js:71:18)
    at ScriptTransformer.transformSource (/node_modules/jest-runtime/build/script_transformer.js:229:35)
    at exports.default (/node_modules/jest-cli/build/generate_empty_coverage.js:37:5)
    at Object.worker (/node_modules/jest-cli/build/reporters/coverage_worker.js:39:291)
    at execMethod (/node_modules/jest-worker/build/child.js:92:29)
    at process.on (/node_modules/jest-worker/build/child.js:42:7)
    at emitTwo (events.js:126:13)

`typescript-compiler.js` is failing `JSON.parse`

this is the component

```
<template>
<footer class="page-footer center-on-small-only">
    <b-container fluid>
    </b-container>
</footer>
</template>

<script lang="ts">
// @ts-ignore
import Component from 'nuxt-class-component'
import Vue from 'vue'

@Component({})
export default class AppFooter extends Vue {
}
```

**Comment by wellnine** [comment]
Have the same issue

**Comment by eddyerburgh** [comment]
Is anybody able to post a reproduction repo?

**Comment by mariangemarcano** [comment]
@eddyerburgh this is an example repo  https://github.com/mariangemarcano/nuxt-typescript-jest-example
running `npm install` and then `npm run test` hits the issue 
it is based on https://github.com/nuxt-community/typescript-template

**Comment by mariangemarcano** [comment]
Just confirmed the issue is fixed in version https://github.com/vuejs/vue-jest/tree/v2.3.0
